### ISSUE TITLE
ارور Failed to send request

### ISSUE THREAD

**Issue by AliShFar** [amirhosseinchoghaei/Increase-openwrt-disk-space#3]
سلام
دستور افزایش دیسک رو که میزنم ارور Failed to send request: Operation not permitted رو میده
مشکل از کجاست؟

**Comment by amirhosseinchoghaei** [comment]
درود مشکل اینترنت هست ، این موارد را رعایت کنید :
رنج آی پی مودم اینترنت دهنده با روتر openwrt یکسان نباشد
دی ان اس ست کنید روی openwrt

**Comment by AliShFar** [comment]
حل شد. خیلی ممنون. مشکل عدم استفاده از ورودی wan روتر بود
