### ISSUE TITLE
x86 with ssd

### ISSUE THREAD

**Issue by saminxx** [amirhosseinchoghaei/Increase-openwrt-disk-space#4]
درود
چجوری از هارد یا ssd یک سیستم x86 استفاده کنیم؟

الان سیستم من 60 گیگ فضا داره ولی این کد شما هم کار نکرد.

**Comment by amirhosseinchoghaei** [comment]
سلام ، این اسکریپت مربوط به فلش مموری هستش طبیعتا کار نمیکنه برای شما !
